env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
  - eslint:recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
  - 'depreciate'
rules: {
  "deprecate/rule-name": 2
}
